{
 "title": "NetgazeX",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Network_receiver_speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_receive_speed_mbps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network_Transmission_speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_transmit_speed_mbps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory_usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU_usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk_usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IP_discovered",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    { "expr": "real_device_ip_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packet_capture",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 5 },
   "targets": [
    { "expr": "packets_captured_details_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OS_detection",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
   "targets": [
    { "expr": "detected_os", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Port_Scan",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "targets": [
    { "expr": "open_ports", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network_Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 13 },
   "targets": [
    { "expr": "vulnerability_risk_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IP_discovered",
   "type": "table",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "Filters",
   "targets": [
    { "expr": "real_device_ip_count", "legendFormat": "__auto" }
   ]
  }
 ]
}